/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAiPredictionRouteImport } from './routes/_app.ai-prediction'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAttendanceHistoryRouteImport } from './routes/_app.attendance-history'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiPredictionRoute = AppAiPredictionRouteImport.update({
  id: '/ai-prediction',
  path: '/ai-prediction',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceHistoryRoute = AppAttendanceHistoryRouteImport.update({
  id: '/attendance-history',
  path: '/attendance-history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kiosk': typeof KioskRoute
  '/signup': typeof SignupRoute
  '/ai-prediction': typeof AppAiPredictionRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance-history': typeof AppAttendanceHistoryRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/payroll': typeof AppPayrollRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kiosk': typeof KioskRoute
  '/signup': typeof SignupRoute
  '/ai-prediction': typeof AppAiPredictionRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance-history': typeof AppAttendanceHistoryRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/payroll': typeof AppPayrollRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kiosk': typeof KioskRoute
  '/signup': typeof SignupRoute
  '/_app/ai-prediction': typeof AppAiPredictionRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance-history': typeof AppAttendanceHistoryRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/forgot-password'
    | '/kiosk'
    | '/signup'
    | '/ai-prediction'
    | '/announcements'
    | '/attendance-history'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/forgot-password'
    | '/kiosk'
    | '/signup'
    | '/ai-prediction'
    | '/announcements'
    | '/attendance-history'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/attendance'
    | '/forgot-password'
    | '/kiosk'
    | '/signup'
    | '/_app/ai-prediction'
    | '/_app/announcements'
    | '/_app/attendance-history'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/payroll'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KioskRoute: typeof KioskRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-prediction': {
      id: '/_app/ai-prediction'
      path: '/ai-prediction'
      fullPath: '/ai-prediction'
      preLoaderRoute: typeof AppAiPredictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-history': {
      id: '/_app/attendance-history'
      path: '/attendance-history'
      fullPath: '/attendance-history'
      preLoaderRoute: typeof AppAttendanceHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppRouteChildren {
  AppAiPredictionRoute: typeof AppAiPredictionRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceHistoryRoute: typeof AppAttendanceHistoryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppPayrollRoute: typeof AppPayrollRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiPredictionRoute: AppAiPredictionRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceHistoryRoute: AppAttendanceHistoryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppPayrollRoute: AppPayrollRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KioskRoute: KioskRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
